ajardin_blizzard_sdk:
    blizzard:
        client_id: 16577200515041bbb28a2f8223ce7828 #"%env(BLIZZARD_CLIENT_ID)%"
        client_secret: LY1jlw4nWCndIzyIfDInyXQAJUMCcGuD #"%env(BLIZZARD_CLIENT_SECRET)%"
